import "./globals.css";
import { Analytics } from "@vercel/analytics/react";

export const metadata = {
  title: "Portfolio - Nguyen An Ninh",
  description: "Generated by Nguyen An Ninh",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
